### ISSUE TITLE
MultipleLanguageTranslationService incompatible with extract-text-webpack-plugin

### ISSUE THREAD

**Issue by agentschmitt** [ckeditor/ckeditor5-dev#425] opened 2018-07-10 14:22 UTC
I can't compile custom build of ckeditor when using CKEditorWebpackPlugin together with ExtractTextPlugin (3.0.2). I also tried using an custom build with webpack4 and mini-css-extract-plugin and got the same error.

When i remove the "additionalLanguages" option from CKEditorWebpackPlugin it is working.

```
Webpack Error:
\ckeditor5-build-inline\node_modules\webpack-sources\lib\ConcatSource.js:23
                        return typeof item === "string" ? item : item.source();
                                                                     ^

TypeError: Cannot read property 'source' of undefined
    at C:\Git\selfserviceportal\Sources\App.Externals\ckeditor5-build-inline\node_modules\webpack-sources\lib\ConcatSource.js:23:49
    at Array.map (native)
    at ConcatSource.source (C:\Git\selfserviceportal\Sources\App.Externals\ckeditor5-build-inline\node_modules\webpack-sources\lib\ConcatSource.js:22:24)
    at writeOut (C:\Git\selfserviceportal\Sources\App.Externals\ckeditor5-build-inline\node_modules\webpack\lib\Compiler.js:331:27)
    at require.forEach (C:\Git\selfserviceportal\Sources\App.Externals\ckeditor5-build-inline\node_modules\webpack\lib\Compiler.js:345:12)
    at C:\Git\selfserviceportal\Sources\App.Externals\ckeditor5-build-inline\node_modules\async\dist\async.js:3110:16
    at eachOfArrayLike (C:\Git\selfserviceportal\Sources\App.Externals\ckeditor5-build-inline\node_modules\async\dist\async.js:1069:9)
    at eachOf (C:\Git\selfserviceportal\Sources\App.Externals\ckeditor5-build-inline\node_modules\async\dist\async.js:1117:5)
    at Object.eachLimit (C:\Git\selfserviceportal\Sources\App.Externals\ckeditor5-build-inline\node_modules\async\dist\async.js:3172:5)
    at emitFiles (C:\Git\selfserviceportal\Sources\App.Externals\ckeditor5-build-inline\node_modules\webpack\lib\Compiler.js:315:21)
    at C:\Git\selfserviceportal\Sources\App.Externals\ckeditor5-build-inline\node_modules\mkdirp\index.js:48:26
    at FSReqWrap.oncomplete (fs.js:123:15)
error Command failed with exit code 1.
```
I used the configuration example from the documentation: https://docs.ckeditor.com/ckeditor5/latest/builds/guides/integration/advanced-setup.html#option-extracting-css

```
Webpack Config:
/**
 * @license Copyright (c) 2003-2018, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md.
 */

'use strict';

/* eslint-env node */

const path = require('path');
const webpack = require('webpack');
const { bundler, styles } = require('@ckeditor/ckeditor5-dev-utils');
const CKEditorWebpackPlugin = require('@ckeditor/ckeditor5-dev-webpack-plugin');
const BabiliPlugin = require('babel-minify-webpack-plugin');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const buildConfig = require('./build-config');

module.exports = {
	devtool: 'source-map',

	entry: path.resolve(__dirname, 'src', 'ckeditor.js'),

	output: {
		path: path.resolve(__dirname, 'build'),
		filename: 'ckeditor.js',
		libraryTarget: 'umd',
		libraryExport: 'default',
		library: buildConfig.moduleName
	},

	plugins: [
		new CKEditorWebpackPlugin({
			language: buildConfig.config.language,
			additionalLanguages: 'all'
		}),
		new BabiliPlugin(null, {
			comments: false
		}),
		new webpack.BannerPlugin({
			banner: bundler.getLicenseBanner(),
			raw: true
		}),
		new ExtractTextPlugin('ckeditor.css'),
		new webpack.optimize.ModuleConcatenationPlugin()
	],

	module: {
		rules: [
			{
				test: /\.svg$/,
				use: ['raw-loader']
			},
			{
				test: /\.css$/,
				use: ExtractTextPlugin.extract({
					fallback: 'style-loader',
					use: [
						{
							loader: 'postcss-loader',
							options: styles.getPostCssConfig({
								themeImporter: {
									themePath: require.resolve('@ckeditor/ckeditor5-theme-lark')
								},
								minify: true
							})
						}
					]
				})
			}
		]
	}
};
```

**Comment by ma2ciek** [comment] 2018-07-10 14:29
Hi @agentschmitt,

Thanks for reporting it, I'll try to reproduce the issue.

**Comment by agentschmitt** [comment] 2018-07-10 14:51
Hi @ma2ciek, 

thanks for help in adavance. I added an pull request to fix this issue.
Not sure if my fix is the best solution. Was the first time i had to do something with the webpack compilation api.

Would be happy if any fix for this can be released soon. Integrating a forked ckeditor5-dev-utils into an custom build seems to be a bit tricky.

greetings Roland

**Comment by Reinmar** [comment] 2018-07-10 14:58
Out of curiosity – did you check the PR with webpack 4 or 3? Two days ago we merged changes which, I think, should make that plugin incompatible with webpack 3. Am I right @ma2ciek ?

**Comment by ma2ciek** [comment] 2018-07-10 15:43
I can confirm the issue. At least for the webpack 3. I wasn't aware of this problem, because we use that combination here: https://github.com/ckeditor/ckeditor5/blob/v10.0.0/scripts/docs/snippetadapter.js#L81. But probably it works here due to the fact, that our entry point is different.

Going into details, the `extract-text-webpack-plugin` plugin injects the `extract-text-webpack-plugin-output-filename` source into webpack assets and the webpack's compilation `optimize-chunk-assets` event is called multiple times with these single source instead of once with all assets. Thus the matching compilation assets equal to 0, which is a not supported edge case (which you handled here https://github.com/ckeditor/ckeditor5-dev/pull/426/files#diff-c7651cbe9bf62ae0195e3db361131b75R169). But I'm unsure about the proposal as it might be buggy in some scenarios.

I'll test it with `webpack@4` and `mini-css-extract-plugin` and try to find out the best solution.

**Comment by ma2ciek** [comment] 2018-07-10 16:11
And I can confirm that for `webpack@4` and `mini-css-extract-plugin` the error shows up too. `mini-css-extract-plugin` injects similar sources into the assets:

```
{ '*':
   CachedSource {
     _source: ConcatSource { children: [Array] },
     _cachedSource: undefined,
     _cachedSize: undefined,
     _cachedMaps: {},
     node: [Function],
     listMap: [Function] } }
```

Anyway, thanks @agentschmitt for the PR and that you dive deep into the issue. I'll merge it or propose another solution tomorrow.

> Two days ago we merged changes which, I think, should make that plugin incompatible with webpack 3. Am I right @ma2ciek ?

Yes, I had to install `@ckeditor/ckeditor5-dev-webpack-plugin@5.0.1` to test it with `webpack@3`.

**Comment by ma2ciek** [comment] 2018-07-10 16:14
> I can confirm the issue. At least for the webpack 3. I wasn't aware of this problem, because we use that combination here: ckeditor/ckeditor5:scripts/docs/snippetadapter.js@v10.0.0#L81. But probably it works here due to the fact, that our entry point is different.

Snippet adapter runs only `SingleLanguageMultipleService`, that's why it doesn't blow up.

**Closed** 2018-07-12 11:33 UTC
